apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservices
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        checksum/config: "${CONFIG_CHECKSUM}" # This will force a pod restart when config changes
    spec:
      containers:
        - name: frontend
          image: wtek01/frontend:0.3.1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: frontend-config
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: ENVIRONMENT
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: API_URL
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: USER_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: ORDER_SERVICE_URL
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: FRONTEND_URL
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          startupProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservices
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP
