apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: feature-frontend-k8s-deployment
  labels:
    app: frontend
data:
  # Build-time Vite environment variables
  VITE_ENVIRONMENT: "kubernetes"
  VITE_API_BASE_URL: "http://api.microservices.local"
  VITE_USER_SERVICE_URL: "http://api.microservices.local/users"
  VITE_ORDER_SERVICE_URL: "http://api.microservices.local/orders"
  VITE_FRONTEND_URL: "http://app.microservices.local"

  # Runtime environment variables
  ENVIRONMENT: "kubernetes"
  API_URL: "http://api.microservices.local"
  USER_SERVICE_URL: "http://api.microservices.local/users"
  ORDER_SERVICE_URL: "http://api.microservices.local/orders"
  FRONTEND_URL: "http://app.microservices.local"
  VERSION: "1.0.0"

  nginx.conf: |
    server {
        listen 80;
        server_name frontend.microservices.local;
        
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
        
        location /api/ {
            proxy_pass http://api.microservices.local/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
  # Add any other frontend configuration as needed








