apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: microservices
  labels:
    app: frontend
data:
  # Build-time Vite environment variables
  VITE_ENVIRONMENT: "kubernetes"
  VITE_API_BASE_URL: "http://api.microservices.local"
  VITE_USER_SERVICE_URL: "http://api.microservices.local/users"
  VITE_ORDER_SERVICE_URL: "http://api.microservices.local/orders"
  VITE_FRONTEND_URL: "http://app.microservices.local"

  # Runtime environment variables
  ENVIRONMENT: "kubernetes"
  API_URL: "http://api.microservices.local"
  USER_SERVICE_URL: "http://api.microservices.local/users"
  ORDER_SERVICE_URL: "http://api.microservices.local/orders"
  FRONTEND_URL: "http://app.microservices.local"
  VERSION: "1.0.0"
