apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: microservices
data:
  VITE_USER_SERVICE_URL: "http://user-service.microservices.svc.cluster.local"
  VITE_ORDER_SERVICE_URL: "http://order-service.microservices.svc.cluster.local"
  VITE_API_BASE_URL: "http://api-gateway.microservices.svc.cluster.local"




