# Mise à jour pour inclure le monitoring avec Prometheus et Grafana
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - zookeeper.yml
  - kafka-statefulset.yml
  - postgres-deployment.yml
  - user-service.yml
  - order-service.yml
  - frontend-deployment.yml
  - frontend-config.yml
  - ingress.yml
  # Les fichiers de monitoring sont maintenant dans le répertoire monitoring/
  # - monitoring/service-monitors.yml

# Ne pas spécifier de namespace ici car les manifestes ont déjà leur namespace défini
# namespace: microservices

# Utiliser labels au lieu de commonLabels pour éviter l'avertissement de dépréciation
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: microservices
