# Configuration Kustomize pour le monitoring
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - monitoring-ingress.yml
  - prometheus-alerts.yml
  - grafana-dashboard-cm.yml
  - service-monitors.yml
  - traffic-generator.yml

namespace: monitoring

commonLabels:
  app.kubernetes.io/part-of: monitoring
  app.kubernetes.io/managed-by: kustomize
